//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_MUSIC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music
    {
        public int ID_Music { get; set; }
        public string Name { get; set; }
        public string Executor { get; set; }
        public string Genre { get; set; }
        public string Duration { get; set; }
        public string Image { get; set; }
    }
}
